resource_group_name = "rg1"
backend_subnet      = "backend"
frontend_subnet     = "frontend"
backend_vm_prefix   = "vmdb"
frontend_vm_prefix  = "vmweb"
admin_username      = "flymetothecloud"
admin_password      = "P@ssw0rd1234"
vm_size             = "Standard_B1s"
